Repository hyva-themes/magento2-hyva-checkout, pull requests merged in 2021-08, with the labels that each got.

#122 #117 issue fix.Typo in reducer filename.
  src/reactapp/src/context/Cart/cartReducer.js
  src/reactapp/src/context/Cart/order/reducers.js
Labels: enhancement

#126 Fixing php code inconsistencies reported in issue-98
  src/Plugin/CheckoutController/Index.php
  src/Plugin/DirectoryModel/SetStateRequired.php
Labels: enhancement

#124 Generic Improvements
  src/reactapp/src/components/CheckoutForm.jsx
  src/reactapp/src/components/billingAddress/BillingAddress.jsx
  src/reactapp/src/components/billingAddress/components/BillingAddressFormikProvider.jsx
  src/reactapp/src/components/paymentMethod/PaymentMethod.jsx
  src/reactapp/src/components/paymentMethod/components/PaymentMethodFormManager.jsx
  src/reactapp/src/components/paymentMethod/context/index.js
  src/reactapp/src/components/paymentMethod/index.js
  src/reactapp/src/components/shippingAddress/ShippingAddress.jsx
  src/reactapp/src/components/shippingAddress/components/ShippingAddressFormikProvider.jsx
  src/reactapp/src/context/Cart/initialState.js
  src/reactapp/src/hook/useFormValidateThenSubmit.js
  src/reactapp/src/utils/form.js
  src/reactapp/src/utils/index.js
  src/view/frontend/web/js/react-checkout.js
  src/view/frontend/web/js/react-checkout.js.map
Labels: enhancement, release-1.0

#131 Issue 104: Use escaper in phtml
  src/view/frontend/templates/react-script.phtml
Labels: enhancement, release-1.0

#129 Use app dispatch in the cart context in the api requests
  src/reactapp/package-lock.json
  src/reactapp/src/context/App/appDispatcher.js
  src/reactapp/src/context/Cart/CartDataProvider.jsx
  src/reactapp/src/context/Cart/billingAddress/actions.js
  src/reactapp/src/context/Cart/cart/actions.js
  src/reactapp/src/context/Cart/cartDispatcher.js
  src/reactapp/src/context/Cart/cartItems/actions.js
  src/reactapp/src/context/Cart/email/actions.js
  src/reactapp/src/context/Cart/order/actions.js
  src/reactapp/src/context/Cart/paymentMethod/actions.js
  src/reactapp/src/context/Cart/shippingAddress/actions.js
  src/reactapp/src/context/Cart/shippingMethod/actions.js
  src/reactapp/src/paymentMethods/paymentConfig.json
  src/view/frontend/web/js/react-checkout.js
  src/view/frontend/web/js/react-checkout.js.map
Labels: bug, release-1.0

#132 Adding environment variable for default country
  src/reactapp/env.example
  src/reactapp/src/config.js
  src/reactapp/src/utils/env.js
  src/view/frontend/web/js/react-checkout.js
  src/view/frontend/web/js/react-checkout.js.map
Labels: enhancement, release-1.0

#134 Cleaning Eslint Configuration Along With Fixes
  src/reactapp/.eslintrc.js
  src/reactapp/src/api/cart/fetchGuestCart/modifier.js
  src/reactapp/src/api/cart/setBillingAddress/setBillingAddress.js
  src/reactapp/src/api/cart/setShippingAddress/modifier.js
  src/reactapp/src/api/cart/utility/query/cartBillingAddrInfo.js
  src/reactapp/src/api/customer/fetchCustomerAddresses/modifier.js
  src/reactapp/src/api/storeConfig/getCheckoutAgreements/modifier.js
  src/reactapp/src/components/address/components/AddressOptions.jsx
  src/reactapp/src/components/address/utility/index.js
  src/reactapp/src/components/billingAddress/components/BillingAddressFormikProvider.jsx
  src/reactapp/src/components/checkoutAgreements/components/CheckoutAgreementModal.jsx
  src/reactapp/src/components/checkoutAgreements/components/CheckoutAgreementsForm.jsx
  src/reactapp/src/components/checkoutAgreements/utility/index.js
  src/reactapp/src/components/common/Button/Button.jsx
  src/reactapp/src/components/common/Button/Button.stories.jsx
  src/reactapp/src/components/common/Card/Card.jsx
  src/reactapp/src/components/common/Card/Card.stories.js
  src/reactapp/src/components/common/Form/Checkbox.jsx
  src/reactapp/src/components/common/Form/Checkbox/Checkbox.stories.jsx
  src/reactapp/src/components/common/Form/Checkbox/index.js
  src/reactapp/src/components/common/Form/RadioInput.jsx
  src/reactapp/src/components/common/Form/RadioInput/RadioInput.stories.jsx
  src/reactapp/src/components/common/Form/RadioInput/index.js
  src/reactapp/src/components/common/Form/SelectInput.jsx
  src/reactapp/src/components/common/Form/SelectInput/SelectInput.stories.jsx
  src/reactapp/src/components/common/Form/SelectInput/index.js
  src/reactapp/src/components/common/Form/TextInput.jsx
  src/reactapp/src/components/common/Form/TextInput/TextInput.stories.jsx
  src/reactapp/src/components/common/Form/TextInput/index.js
  src/reactapp/src/components/common/Header/Header.jsx
  src/reactapp/src/components/common/Loader/Loader.jsx
  src/reactapp/src/components/common/ToggleBox/ToggleBox.stories.jsx
  src/reactapp/src/components/items/components/CartItemsFormManager/CartItemsFormManager.jsx
  src/reactapp/src/components/login/components/LoginForm.jsx
  src/reactapp/src/components/paymentMethod/index.js
  src/reactapp/src/components/shippingAddress/components/ShippingAddressFormikProvider.jsx
  src/reactapp/src/hook/useFormikMemorizer.js
  src/reactapp/src/i18n/__.js
  src/reactapp/src/tailwind.config.js
  src/reactapp/src/utils/index.js
  src/reactapp/src/utils/price.js
  src/view/frontend/web/js/react-checkout.js
  src/view/frontend/web/js/react-checkout.js.map
Labels: enhancement, release-1.0

#135 Issue 112: Avoid event.keyCode usage
  src/reactapp/src/components/checkoutAgreements/components/CheckoutAgreementModalWrapper.jsx
  src/reactapp/src/hook/useEnterActionInForm.js
  src/view/frontend/web/js/react-checkout.js
  src/view/frontend/web/js/react-checkout.js.map
Labels: enhancement, release-1.0

#137 Warning message for TextInput component in the browser console
  src/reactapp/src/components/common/Form/TextInput.jsx
  src/view/frontend/web/js/react-checkout.js
  src/view/frontend/web/js/react-checkout.js.map
Labels: bug, release-1.0

#142 Add documentation site link in README
  README.md
Labels: documentation, enhancement, release-1.0
